steps:
  - name: "python:latest"
  entrypoint: "bash"
  args:
    - "-c"
    - "pip install flask && python -m unittest discover -v flaskapp"
  id: "unit-test"
  # - name: "python:latest"
  #   entrypoint: "python"
  #   args: ["-m", "unittest", "discover", "flaskapp"]
  #   id: "unit-test"
  - name: "python:latest"
    waitFor: ["unit-test"]
    entrypoint: "bash"
    args: ["-c", "echo", "unit test passed!"]
  - name: "gcr.io/cloud-builders/docker"
    entrypoint: docker
    args:
      - "build"
      - "-t"
      - "us-central1-docker.pkg.dev/dlegesse-test/test-project/webapp1:1.0"
      - "-f"
      - "flaskapp/Dockerfile"
      - "flaskapp"
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "push"
      - "us-central1-docker.pkg.dev/dlegesse-test/test-project/webapp1:1.0"
images:
  - "us-central1-docker.pkg.dev/dlegesse-test/test-project/webapp1:1.0"
options:
  logging: CLOUD_LOGGING_ONLY
