steps:
  - name: "python:latest"
    entrypoint: "bash"
    args:
      - "-c"
      - "pip install flask flask_cors && python -m unittest discover -v flaskapp"
    id: "unit-test"
  - name: "python:latest"
    waitFor: ["unit-test"]
    entrypoint: "bash"
    args: ["-c", "echo", "unit test passed!"]
  - name: "gcr.io/cloud-builders/docker"
    entrypoint: docker
    args:
      - "build"
      - "-t"
      - "us-central1-docker.pkg.dev/dlegesse-test/test-project/webapp1:1.2"
      - "-f"
      - "flaskapp/Dockerfile"
      - "flaskapp"
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "push"
      - "us-central1-docker.pkg.dev/dlegesse-test/test-project/webapp1:1.2"
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      - "run"
      - "deploy"
      - "webapp1"
      - "--image"
      - "us-central1-docker.pkg.dev/dlegesse-test/test-project/webapp1:1.2"
      - "--region"
      - "us-central1"
      - "--platform"
      - "managed"
      - "--allow-unauthenticated"
  - name: "gcr.io/cloud-builders/gsutil"
    entrypoint: gsutil
    args:
      - "-m"
      - "cp"
      - "-r"
      - "frontend/"
      - "gs://$_BUCKET_NAME"
images:
  - "us-central1-docker.pkg.dev/dlegesse-test/test-project/webapp1:1.2"
options:
  logging: CLOUD_LOGGING_ONLY
substitutions:
  _BUCKET_NAME: "webapp-dlegesse-test"
